#!/bin/bash
# Daily automated MCP protocol test — pulls latest test code from GitHub,
# runs the suite, alerts on anything that needs a human.
#
# Э0 hygiene pass (Fable's audit, 2026-09-02). Deliberately NOT `set -e`:
# every step that can legitimately fail (git fetch/rebase, npm install, the
# test run itself) is handled explicitly with its own alert + fallback, so
# the script always reaches its own retention/heartbeat tail rather than
# dying silently partway through on an unguarded command.
set -uo pipefail
cd /home/apibase/mcp-protocol-tester

TIMESTAMP=$(date +%Y%m%d_%H%M%S)
LOG="reports/daily-${TIMESTAMP}.log"
mkdir -p reports
: > "$LOG"

notify() {
  # Best-effort Telegram page — never blocks the run if it fails.
  bash scripts/notify-telegram.sh "$1" >> "$LOG" 2>&1 \
    || echo "[$(date +%Y%m%d_%H%M%S)] Telegram notify failed (see log above)" >> "$LOG"
}

# --- Pull latest test code --------------------------------------------------
# Was `git rebase ... || git reset --hard origin/main || true` — the same
# defect class as apibase's own deploy.sh: a failed rebase silently
# destroyed any uncommitted tracked-file edit, every morning, under a
# `2>/dev/null || true` nobody ever looked at. Now: a dirty tracked tree or
# a failed rebase ALERTS and runs whatever is already checked out — the old
# working tester is better than a fresh one that just ate someone's edits.
if ! git diff --quiet 2>>"$LOG" || ! git diff --cached --quiet 2>>"$LOG"; then
  notify "[apibase tester] ⚠️ run-daily.sh: tracked working tree is dirty — skipping git pull, running the code AS CHECKED OUT (no reset --hard)."
  echo "[$TIMESTAMP] Dirty tracked tree — skipped pull, running existing checkout" >> "$LOG"
else
  if git fetch origin main --quiet >> "$LOG" 2>&1; then
    if ! git rebase origin/main --quiet >> "$LOG" 2>&1; then
      git rebase --abort >> "$LOG" 2>&1 || true
      notify "[apibase tester] ⚠️ run-daily.sh: git rebase onto origin/main failed — running the last known-good checkout instead (no reset --hard)."
      echo "[$TIMESTAMP] Rebase failed — running existing checkout" >> "$LOG"
    fi
  else
    notify "[apibase tester] ⚠️ run-daily.sh: git fetch failed — running the last known-good checkout."
    echo "[$TIMESTAMP] git fetch failed — running existing checkout" >> "$LOG"
  fi
fi

if ! npm install --quiet >> "$LOG" 2>&1; then
  notify "[apibase tester] ⚠️ run-daily.sh: npm install failed — running with the existing node_modules."
  echo "[$TIMESTAMP] npm install failed — continuing with existing node_modules" >> "$LOG"
fi

# --- Run the test ------------------------------------------------------------
# Э6: TESTER_RUN_ID is the X-APIbase-Tester value every request this run
# makes will carry (see src/lib/http.js) — stable per run, correlatable with
# this exact log file.
export TESTER_RUN_ID="daily-${TIMESTAMP}"
echo "[${TIMESTAMP}] Starting daily MCP protocol test (run id ${TESTER_RUN_ID})..." >> "$LOG"
timeout 600 node --max-old-space-size=512 src/index.js >> "$LOG" 2>&1
TEST_EXIT=$?

JSON_REPORT=$(ls -t reports/dual-rail-report-*.json 2>/dev/null | head -1)

if [ -z "$JSON_REPORT" ]; then
  notify "[apibase tester] 🔴 run-daily.sh: the test run produced NO report at all (node exit ${TEST_EXIT}) — it crashed or was killed mid-run. See cron.log on the box."
  echo "[$(date +%Y%m%d_%H%M%S)] No JSON report produced (node exit ${TEST_EXIT}) — treated as a hard failure" >> "$LOG"
else
  # Report is the single source of truth for score/grade/verdict — read it,
  # don't re-derive it by grepping the text log.
  eval "$(node -e "
    const r = require('$PWD/$JSON_REPORT');
    console.log('SCORE=' + r.score);
    console.log('GRADE=' + r.grade);
    console.log('VERDICT=' + r.verdict);
  ")"
  echo "[$(date +%Y%m%d_%H%M%S)] Score: ${SCORE}/100 Grade: ${GRADE} Verdict: ${VERDICT} (node exit ${TEST_EXIT})" >> "$LOG"

  # --- Э1: verdict + standing-red ledger / diff / escalation ----------------
  ALERT_MSG=$(node scripts/verdict-runner.js "$JSON_REPORT" 2>>"$LOG")
  ALERT_NEEDED=$?
  echo "$ALERT_MSG" >> "$LOG"

  if [ "$ALERT_NEEDED" != "0" ]; then
    notify "$ALERT_MSG"
    ISSUE_TITLE="[Auto-Test] Score ${SCORE}/100 (${GRADE}) Verdict ${VERDICT} — $(date +%Y-%m-%d)"
    ISSUE_BODY="$ALERT_MSG

---
Full log: reports/daily-${TIMESTAMP}.log on the tester box.
*Auto-generated by [mcp-protocol-tester](https://github.com/whiteknightonhorse/mcp-protocol-tester) daily cron*"

    # Dedup: a run that keeps failing the same way (e.g. P26's real
    # coverage gaps, until someone adds probes or exempts them) must not
    # open a fresh GitHub issue every single day — issue is a journal, not
    # a per-run event. Reuse the existing open [Auto-Test] issue if there
    # is one; only open a new one otherwise.
    EXISTING_ISSUE=$(gh issue list --repo whiteknightonhorse/APIbase \
      --search "[Auto-Test] in:title" --state open --json number --jq '.[0].number' 2>>"$LOG")
    if [ -n "$EXISTING_ISSUE" ]; then
      gh issue comment "$EXISTING_ISSUE" --repo whiteknightonhorse/APIbase --body "${ISSUE_BODY}" \
        >> "$LOG" 2>&1 || echo "[$(date +%Y%m%d_%H%M%S)] Failed to comment on issue #${EXISTING_ISSUE}" >> "$LOG"
    else
      gh issue create \
        --repo whiteknightonhorse/APIbase \
        --title "${ISSUE_TITLE}" \
        --body "${ISSUE_BODY}" \
        >> "$LOG" 2>&1 || echo "[$(date +%Y%m%d_%H%M%S)] Failed to create GitHub issue" >> "$LOG"
    fi
  else
    echo "[$(date +%Y%m%d_%H%M%S)] All good — no alert needed (score=${SCORE}, verdict=${VERDICT})" >> "$LOG"
  fi
fi

# --- Э5: internal truth (Ярус C) --------------------------------------------
# White-box, same box: crontab/systemd vs apibase's own documented job table,
# and the served-pair (git HEAD vs running image / static-current symlink).
# Separate from the P0-P26 HTTP corpus and from the standing-red ledger above
# on purpose — a drift here is infrastructure truth, not a probe result.
TRUTH_OUT=$(node scripts/internal-truth.js 2>&1)
TRUTH_EXIT=$?
echo "$TRUTH_OUT" >> "$LOG"
if [ "$TRUTH_EXIT" != "0" ]; then
  notify "[apibase tester] ⚠️ internal-truth (Э5) drift:
$TRUTH_OUT"
fi

# --- Э4: publish the dead-man heartbeat --------------------------------------
# Only on a run that actually finished and produced a report — a crashed run
# must NOT refresh the heartbeat, or the outer smoke tier's "deep report
# younger than 26h" dead-man switch would never fire for the one case it
# exists to catch.
if [ -n "$JSON_REPORT" ]; then
  {
    date -u +%Y-%m-%dT%H:%M:%SZ
    echo "score=${SCORE} grade=${GRADE} verdict=${VERDICT}"
  } > reports/.heartbeat
  git add reports/.heartbeat >> "$LOG" 2>&1
  if git diff --cached --quiet; then
    : # heartbeat content unchanged (shouldn't happen — timestamp always differs)
  elif git commit -m "chore: heartbeat ${TIMESTAMP}" >> "$LOG" 2>&1; then
    git push >> "$LOG" 2>&1 \
      || echo "[$(date +%Y%m%d_%H%M%S)] heartbeat push failed (non-fatal — next run's fetch/rebase will retry)" >> "$LOG"
  else
    echo "[$(date +%Y%m%d_%H%M%S)] heartbeat commit failed (non-fatal)" >> "$LOG"
  fi
fi

# --- Retention ---------------------------------------------------------------
# Keep only the last 30 daily-*.log (unchanged from before). dual-rail-*
# older than 30 days is removed outright. Backstop: the reports/ directory
# must not exceed 90 files total — if it still does after the above, delete
# the oldest until it does. Fable's audit: 840 dual-rail-* files had piled
# up since March because only daily-*.log was ever capped.
ls -t reports/daily-*.log 2>/dev/null | tail -n +31 | xargs -r rm -f
find reports -maxdepth 1 -name 'dual-rail-*' -mtime +30 -delete 2>/dev/null

REPORT_COUNT=$(find reports -maxdepth 1 -type f ! -name '.gitkeep' ! -name '.heartbeat' ! -name 'standing-reds.json' | wc -l)
if [ "$REPORT_COUNT" -gt 90 ]; then
  EXCESS=$((REPORT_COUNT - 90))
  find reports -maxdepth 1 -type f ! -name '.gitkeep' ! -name '.heartbeat' ! -name 'standing-reds.json' -printf '%T@ %p\n' \
    | sort -n | head -n "$EXCESS" | cut -d' ' -f2- | xargs -r rm -f
  echo "[$(date +%Y%m%d_%H%M%S)] Retention: removed ${EXCESS} oldest report file(s) to stay <= 90" >> "$LOG"
fi

exit 0
