#!/bin/bash
# Daily automated MCP protocol test
# Pulls latest tests from GitHub, runs, creates GitHub Issue on failure

set -euo pipefail
cd /home/apibase/mcp-protocol-tester

# Pull latest test updates (--rebase to handle divergent branches)
git fetch origin main --quiet 2>/dev/null || true
git rebase origin/main --quiet 2>/dev/null || git reset --hard origin/main 2>/dev/null || true
npm install --quiet 2>/dev/null || true

# Run test
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
LOG="reports/daily-${TIMESTAMP}.log"

echo "[${TIMESTAMP}] Starting daily MCP protocol test..." > "$LOG"
timeout 600 node --max-old-space-size=512 src/index.js >> "$LOG" 2>&1 || true

# Parse results from log
SCORE=$(grep -oP 'Score \K[0-9]+' "$LOG" | tail -1 || echo "0")
GRADE=$(grep -oP 'Grade \K[A-F][+-]?' "$LOG" | tail -1 || echo "?")
ERRORS_500=$(grep -oP '500 SERVER ERRORS \(\K[0-9]+' "$LOG" | tail -1 || echo "0")
PASS=$(grep -oP 'Pass: \K[0-9]+' "$LOG" | tail -1 || echo "0")
FAIL=$(grep -oP 'Fail: \K[0-9]+' "$LOG" | tail -1 || echo "0")
TOTAL=$(grep -oP 'total$' "$LOG" | wc -l || echo "0")

echo "[$(date +%Y%m%d_%H%M%S)] Score: ${SCORE}/100 Grade: ${GRADE} | Pass: ${PASS} Fail: ${FAIL} | 500 errors: ${ERRORS_500}" >> "$LOG"

# Keep only last 30 reports
ls -t reports/daily-*.log 2>/dev/null | tail -n +31 | xargs rm -f 2>/dev/null

# --- GitHub Issue on failure ---
# Create issue if: score < 80, or any 500 errors, or test crashed
SHOULD_ALERT=false

if [ "${SCORE:-0}" -lt 80 ] 2>/dev/null; then
  SHOULD_ALERT=true
fi

if [ "${ERRORS_500:-0}" -gt 0 ] 2>/dev/null; then
  SHOULD_ALERT=true
fi

if [ "$SHOULD_ALERT" = true ]; then
  # Extract failure summary (last 50 lines of failures)
  FAILURES=$(grep "\[FAIL\]\|\[P[0-9]\].*FAIL\|500\|CRITICAL" "$LOG" | tail -30)
  PHASE_SCORES=$(grep "^  P[0-9]" "$LOG" | head -15)

  # Create GitHub Issue
  ISSUE_TITLE="[Auto-Test] Score ${SCORE}/100 (${GRADE}) — $(date +%Y-%m-%d)"
  ISSUE_BODY="$(cat <<ISSUE_EOF
## Daily MCP Protocol Test — ${GRADE}

**Score:** ${SCORE}/100
**Date:** $(date -u +%Y-%m-%dT%H:%M:%SZ)
**Pass/Fail:** ${PASS}/${FAIL}
**500 Errors:** ${ERRORS_500}

### Phase Scores
\`\`\`
${PHASE_SCORES}
\`\`\`

### Failures
\`\`\`
${FAILURES}
\`\`\`

### Action Required
$(if [ "${ERRORS_500:-0}" -gt 0 ]; then echo "- **CRITICAL:** Server 500 errors detected — investigate immediately"; fi)
$(if [ "${SCORE:-0}" -lt 70 ]; then echo "- **HIGH:** Score below 70 — significant regression"; elif [ "${SCORE:-0}" -lt 80 ]; then echo "- **MEDIUM:** Score below 80 — review failures"; fi)

---
*Auto-generated by [mcp-protocol-tester](https://github.com/whiteknightonhorse/mcp-protocol-tester) daily cron*
ISSUE_EOF
)"

  # Post to GitHub (uses gh CLI auth)
  gh issue create \
    --repo whiteknightonhorse/APIbase \
    --title "${ISSUE_TITLE}" \
    --body "${ISSUE_BODY}" \
    2>> "$LOG" || echo "Failed to create GitHub issue" >> "$LOG"

  echo "[$(date +%Y%m%d_%H%M%S)] GitHub Issue created (score=${SCORE}, 500s=${ERRORS_500})" >> "$LOG"
else
  echo "[$(date +%Y%m%d_%H%M%S)] All good — no issue needed (score=${SCORE}, grade=${GRADE})" >> "$LOG"
fi

# Auto-feedback: track score regression for Claude memory
PREV_REPORT=$(ls -t "$REPORT_DIR"/daily-*.log 2>/dev/null | sed -n '2p')
if [ -n "$PREV_REPORT" ]; then
  PREV_SCORE=$(grep -oP 'Score: \K[0-9]+' "$PREV_REPORT" 2>/dev/null | tail -1 || echo "0")
  if [ "${SCORE:-0}" -lt "${PREV_SCORE:-0}" ]; then
    # Score dropped — log regression for Claude to pick up
    MEMORY_DIR="/home/apibase/.claude/projects/-home-apibase-apibase/memory"
    REGRESSION_FILE="$MEMORY_DIR/project_test_regression.md"
    cat > "$REGRESSION_FILE" << REGEOF
---
name: Test score regression detected
description: mcp-protocol-tester score dropped from ${PREV_SCORE} to ${SCORE} on $(date +%Y-%m-%d)
type: project
---

Protocol tester score regression: ${PREV_SCORE} → ${SCORE} on $(date +%Y-%m-%d).

**Why:** Check recent code changes that may have broken test assertions.

**How to apply:** Run \`/test-quick\` to identify failing phases. Check git log for changes since last passing run.
REGEOF
    echo "[$(date +%Y%m%d_%H%M%S)] Score regression: ${PREV_SCORE} → ${SCORE} — memory updated" >> "$LOG"
  fi

  # Flywheel: new failures → auto-create rules
  PREV_FAILURES=$(grep "\[FAIL\]" "$PREV_REPORT" 2>/dev/null | sort || true)
  CURR_FAILURES=$(grep "\[FAIL\]" "$LOG" 2>/dev/null | sort || true)
  NEW_FAILURES=$(comm -13 <(echo "$PREV_FAILURES") <(echo "$CURR_FAILURES") 2>/dev/null || true)
  if [ -n "$NEW_FAILURES" ]; then
    echo "$NEW_FAILURES" | head -5 | while IFS= read -r fail; do
      FAIL_NAME=$(echo "$fail" | grep -oP '\] \K.*?(?= —)' | head -1)
      if [ -n "$FAIL_NAME" ]; then
        /home/apibase/apibase/scripts/flywheel-update.sh \
          "Protocol test NEW failure: $FAIL_NAME" \
          "Investigate and fix: $FAIL_NAME. Check recent code changes that may have caused regression." \
          "testing" 2>/dev/null || true
      fi
    done
    echo "[$(date +%Y%m%d_%H%M%S)] Flywheel: $(echo "$NEW_FAILURES" | wc -l) new failure rules created" >> "$LOG"
  fi
fi
